# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-app"
client_id = "f68a3b9a18faa115c89fe65cf681036c"
application_url = "https://women-hard-supposed-showing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://women-hard-supposed-showing.trycloudflare.com/auth/callback",
  "https://women-hard-supposed-showing.trycloudflare.com/auth/shopify/callback",
  "https://women-hard-supposed-showing.trycloudflare.com/api/auth/callback",
  "https://women-hard-supposed-showing.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bright-cellars-test.myshopify.com"
